### ISSUE TITLE
Lots of negative numbers in the tests increase column.

### ISSUE THREAD

**Issue by discstalker** [COVID19Tracking/issues#314]
lots of -46151 in the tests increase column today. Many states have the same number and all are in the first week of March except Massachusetts today...

**Comment by careeningspace** [comment]
Hello, 

Thank you for the catch. During an update to the MA numbers, I mistakenly used the total tested for the Negatives column. This has been corrected.

Can you tell me which other states you are seeing an issue with?


Date | State | Positive | Negative
-- | -- | -- | --
20200427 | MA | 56462 | 188425
20200426 | MA | 54938 | 181162
20200425 | MA | 53348 | 173497
20200424 | MA | 50969 | 164244
20200423 | MA | 47992 | 156324
20200422 | MA | 44913 | 144789
20200421 | MA | 43168 | 141444
20200420 | MA | 41416 | 136046
20200419 | MA | 39820 | 129295
20200418 | MA | 37527 | 124604
20200417 | MA | 35125 | 117195
20200416 | MA | 32492 | 110098
20200415 | MA | 29970 | 102790
20200414 | MA | 28109 | 98820
20200413 | MA | 26794 | 95500
20200412 | MA | 25381 | 91463
20200411 | MA | 22766 | 86115
20200410 | MA | 20878 | 81564
20200409 | MA | 18843 | 76146
20200408 | MA | 16692 | 70849
20200407 | MA | 15104 | 66270
20200406 | MA | 13739 | 62720
20200405 | MA | 12402 | 59565
20200404 | MA | 11637 | 57191
20200403 | MA | 10303 | 52685
20200402 | MA | 8867 | 47767
20200401 | MA | 7639 | 44125
20200331 | MA | 6521 | 40440
20200330 | MA | 5653 | 37166
20200329 | MA | 4856 | 34234
20200328 | MA | 4158 | 30915
20200327 | MA | 3151 | 26244
20200326 | MA | 2318 | 21327
20200325 | MA | 1739 | 18079
20200324 | MA | 1060 | 12714
20200323 | MA | 678 | 8263
20200322 | MA | 547 | 5476
20200321 | MA | 426 | 4799
20200320 | MA | 314 | 3795
20200319 | MA | 229 | 2918
20200318 | MA | 156 | 2115
20200317 | MA | 118 | 1633
20200316 | MA | 97 | 1199
20200315 | MA | 64 | 584
20200314 | MA | 38 |  
20200313 | MA | 23 |  
20200312 | MA | 8 |

**Comment by discstalker** [comment]
The data refresh I did at 6:10pm has all of these as well...

4/27/2020 18 1 Monday 2 Massachusetts -46151
3/12/2020 11 4 Thursday 1 Massachusetts -46151
3/7/2020 10 6 Saturday 1 Maine -46151
3/7/2020 10 6 Saturday 1 Montana -46151
3/7/2020 10 6 Saturday 1 Idaho -46151
3/7/2020 10 6 Saturday 1 Hawaii -46151
3/7/2020 10 6 Saturday 1 Utah -46151
3/7/2020 10 6 Saturday 1 Oklahoma -46151
3/7/2020 10 6 Saturday 1 South Dakota -46151
3/6/2020 10 5 Friday 1 Kansas -46151
3/6/2020 10 5 Friday 1 Kentucky -46151
3/6/2020 10 5 Friday 1 Indiana -46151
3/6/2020 10 5 Friday 1 Delaware -46151
3/6/2020 10 5 Friday 1 Iowa -46151
3/6/2020 10 5 Friday 1 Vermont -46151
3/6/2020 10 5 Friday 1 West Virginia -46151
3/6/2020 10 5 Friday 1 Pennsylvania -46151
3/6/2020 10 5 Friday 1 Minnesota -46151
3/6/2020 10 5 Friday 1 New Mexico -46151
3/6/2020 10 5 Friday 1 Alaska -46151
3/6/2020 10 5 Friday 1 Arkansas -46151
3/5/2020 10 4 Thursday 1 Colorado -46151
3/5/2020 10 4 Thursday 1 New Jersey -46151
3/5/2020 10 4 Thursday 1 Nevada -46151
3/5/2020 10 4 Thursday 1 Nebraska -46151
3/5/2020 10 4 Thursday 1 District Of Columbia -46151
3/5/2020 10 4 Thursday 1 Maryland -46151
3/5/2020 10 4 Thursday 1 Virginia -46151
3/5/2020 10 4 Thursday 1 Ohio -46151
3/5/2020 10 4 Thursday 1 Tennessee -46151
3/4/2020 10 3 Wednesday 1 North Carolina -46151
3/4/2020 10 3 Wednesday 1 New Hampshire -46151
3/4/2020 10 3 Wednesday 1 Illinois -46151
3/4/2020 10 3 Wednesday 1 Florida -46151
3/4/2020 10 3 Wednesday 1 Georgia -46151
3/4/2020 10 3 Wednesday 1 Texas -46151
3/4/2020 10 3 Wednesday 1 Wisconsin -46151
3/4/2020 10 3 Wednesday 1 South Carolina -46151
3/4/2020 10 3 Wednesday 1 New York -46151
3/4/2020 10 3 Wednesday 1 Oregon -46151
3/4/2020 10 3 Wednesday 1 Arizona -46151
3/4/2020 10 3 Wednesday 1 California -46151
3/1/2020 10 0 Sunday 1 Rhode Island -46151
3/1/2020 10 0 Sunday 1 Michigan -46151
1/22/2020 4 3 Wednesday 1 Washington -46151



------ Original Message ------

**Comment by john2014** [comment]
In the Apr 28 refresh, for States Historical Data, the following fields have negative value 

1. For totalTestResultsIncrease: 

20200425 | LA | -4714
20200423 | WY | -56
20200422 | DE | -103
20200422 | PR | -330
20200413 | AK | -208
20200411 | DE | -638
20200330 | WI | -585

2. For positiveIncrease

20200422 | HI | -2
20200422 | PR | -383
20200307 | RI | -1

3.  For negativeIncrease

20200425 | LA
20200423 | WY
20200422 | DE
20200413 | AK
20200411 | DE
20200330 | WI

There are many more columns in both csv files: US Historical Data and States Historical Data which have negative value in them. You can easily find these columns by autofiltering column which has "-" in it.

Another data issue is that in both these csv files, the value of ICU currently and Ventilator currently is (a) greater than ICU cumulative and Ventilator cumulative and (b) the cumulative values for these two columns keeps decreasing for future dates.

Any ETA  when all these issue could be resolved?  Thank you for your help 😄

**Comment by discstalker** [comment]
Same data I have today, I refreshed this morning and all the problems 
went away...

Feel free to close...

Dave

------ Original Message ------

**Comment by muamichali** [comment]
Thanks for letting us know, Dave! Glad the issues are resolved.

**Comment by john2014** [comment]
FYI...the issues I reported (for negative values) are still present in multiple files. Should I open a new issue for those?
